### ISSUE TITLE
Instrument location and new instruments on Zynthian

### ISSUE THREAD

**Issue by Beltshassar** [ssj71/reMID.lv2#6]
Should the new instruments show up automagically after recompiling?

I've install reMID 0.1 on my Zynthian and tried to compile 0.3.
But there's only 9 instruments available (from 0.1 I guess).
The new ones doesn't show up. Neither do the ones I've tried to make myself.

This is the path were the instruments are located:

root@zynthian:~# ll /usr/local/lib/lv2/remid.lv2/
total 436
-rw-r--r-- 1 root root 511 Apr 26 20:47 bass_big0c.conf
-rw-r--r-- 1 root root 827 Apr 26 20:47 blank.conf
-rw-r--r-- 1 root root 420 Mar 12 20:12 bubbley.conf
-rw-r--r-- 1 root root 423 Mar 12 20:12 digital_spill.conf
-rw-r--r-- 1 root root 1294 Mar 12 20:12 drumkit.conf
-rw-r--r-- 1 root root 915 Apr 26 20:47 fallingAngel.conf
-rw-r--r-- 1 root root 2118 Mar 12 20:12 instruments.conf
-rw-r--r-- 1 root root 257 Mar 12 20:12 manifest.ttl
-rw-r--r-- 1 root root 448 Apr 26 20:47 octave_siren.conf
-rw-r--r-- 1 root root 433 Mar 12 20:12 organ.conf
-rw-r--r-- 1 root root 829 Apr 26 20:47 paddy.conf
-rw-r--r-- 1 root root 517 Mar 12 20:12 piano.conf
-rw-r--r-- 1 root root 623 Mar 13 10:44 piano_test.conf
-rw-r--r-- 1 root root 807 Mar 12 20:12 pulsething.conf
-rw-r--r-- 1 root root 355380 May 5 19:18 remid.lv2.so
-rw-r--r-- 1 root root 6744 Mar 12 20:15 remid.ttl
-rw-r--r-- 1 root root 1272 Mar 12 20:12 riser.conf
-rw-r--r-- 1 root root 717 Mar 12 20:12 saw2sqr.conf
-rw-r--r-- 1 root root 738 Mar 12 20:12 saws.conf
-rw-r--r-- 1 root root 717 Mar 12 20:12 sqr2saw.conf
-rw-r--r-- 1 root root 796 Mar 12 20:12 subsynth.conf
-rw-r--r-- 1 root root 794 May 5 19:22 test.conf

-- this might be something Zynthian specific or -most likely- my lack of git+compiling skills

**Comment by ssj71** [comment]
thanks for making a new issue for this.

I guess the first question is where are you putting the new presets you are creating? When you install every file In the instruments directory should be copied in that directory you show. So you can just put them there and it should work out. 

The other question is how exactly you are expecting them to "show up." I haven't finished building my zynthian yet, so I'm not sure how it works. On desktop with jalv as an lv2 host I'm able to just open a file browser from the jalv GUI and select whatever file I want. I suspect with zynthian, jalv is running without its usual UI so that doesn't work. I suspect what you are seeing are the presets. Those ones I added to the plugin .ttl metadata. See https://github.com/ssj71/reMID.lv2/blob/master/src/remid.ttl#L101

You could add more lines like that for the files you want or perhaps even better would be to make a new manifest.ttl file with all your presets so that you don't have to worry about messing up the plugin with a fat-finger typo or something. Those presets were only added for hosts that don't have any file browser option (mostly qtractor at the time) but long term its probably best if we figure out a way to add a file browser to the usual zynthain workflow. This would apply to things like impulse response plugins as well. We should probably open a thread on the zynthian forums about it. For starters though you can make some new presets in the .ttl. Does that make any sense?

**Comment by Beltshassar** [comment]
I did put the instrument files in  /usr/local/lib/lv2/remid.lv2
But as you suggest, there's no file browser in jalv running on zynthian.

I tried to add a new section to the manifest.ttl file. Which gave me exactly what I wanted, a new instrument in the Zynthian interface. So again you're spot on: jalv on Zynthian must be loading the .ttl preset file.

I've seen a section for uploading presets inside the Zynthian webui, so I guess it should be possible to add reMID presets that way or even better, if we could upload instrument configs directly and have zynthian list those. But that is definitely a topic for another forum.

There's still some performance issues, but at least I can try out some different instruments by now.

Thanks for your reply, I guess I understand a bit more about lv2 by now 👍
You should really get your Zynthian box together, I'm sure you'll love it.
